/** Narrative content generated by OpenAI — never includes computed probabilities */
export interface FighterNarrativeProfile {
  strengths: string[]
  weaknesses: string[]
}

export interface FightNarrativeAnalysis {
  /** Written fight preview (2–4 short paragraphs) */
  analysis: string
  redCorner: FighterNarrativeProfile
  blueCorner: FighterNarrativeProfile
  /** Deciding factors / keys to watch */
  fightKeys: string[]
  generatedAt: string
  /** OpenAI model id used */
  providerModel: string
}

export interface FightAnalysisResponse {
  /** Statistical prediction — sole source of probabilities */
  prediction: {
    fighterAProbability: number
    fighterBProbability: number
    confidence: number
    predictedMethod: string
    predictedRound: number
    predictedWinnerId: string
  }
  narrative: FightNarrativeAnalysis
}
