/** Normalise un libellé pays (roster, sync UFC, etc.) pour lookup drapeau. */
function normalizeCountryKey(raw: string): string {
  return raw
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]/g, '')
}

const COUNTRY_FLAGS: Record<string, string> = {
  algeria: '🇩🇿',
  argentina: '🇦🇷',
  armenia: '🇦🇲',
  australia: '🇦🇺',
  austria: '🇦🇹',
  azerbaijan: '🇦🇿',
  ba: '🇧🇦',
  belarus: '🇧🇾',
  bahrain: '🇧🇭',
  belgium: '🇧🇪',
  bh: '🇧🇭',
  bhr: '🇧🇭',
  bih: '🇧🇦',
  bosnia: '🇧🇦',
  brazil: '🇧🇷',
  br: '🇧🇷',
  bra: '🇧🇷',
  brasil: '🇧🇷',
  bgr: '🇧🇬',
  bulgaria: '🇧🇬',
  cameroon: '🇨🇲',
  canada: '🇨🇦',
  can: '🇨🇦',
  chile: '🇨🇱',
  china: '🇨🇳',
  chn: '🇨🇳',
  cn: '🇨🇳',
  colombia: '🇨🇴',
  croatia: '🇭🇷',
  cuba: '🇨🇺',
  cu: '🇨🇺',
  cub: '🇨🇺',
  czechia: '🇨🇿',
  czechrepublic: '🇨🇿',
  cze: '🇨🇿',
  denmark: '🇩🇰',
  deutschland: '🇩🇪',
  de: '🇩🇪',
  deu: '🇩🇪',
  ecuador: '🇪🇨',
  egypt: '🇪🇬',
  england: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  espana: '🇪🇸',
  es: '🇪🇸',
  esp: '🇪🇸',
  estonia: '🇪🇪',
  etatsunis: '🇺🇸',
  finland: '🇫🇮',
  france: '🇫🇷',
  fr: '🇫🇷',
  fra: '🇫🇷',
  gb: '🇬🇧',
  gbr: '🇬🇧',
  georgia: '🇬🇪',
  geo: '🇬🇪',
  arm: '🇦🇲',
  kaz: '🇰🇿',
  nga: '🇳🇬',
  nzl: '🇳🇿',
  germany: '🇩🇪',
  greece: '🇬🇷',
  holland: '🇳🇱',
  hrv: '🇭🇷',
  hungary: '🇭🇺',
  iceland: '🇮🇸',
  id: '🇮🇩',
  idn: '🇮🇩',
  ie: '🇮🇪',
  india: '🇮🇳',
  indonesia: '🇮🇩',
  iran: '🇮🇷',
  iraq: '🇮🇶',
  ireland: '🇮🇪',
  irl: '🇮🇪',
  israel: '🇮🇱',
  it: '🇮🇹',
  ita: '🇮🇹',
  italy: '🇮🇹',
  japan: '🇯🇵',
  jpn: '🇯🇵',
  kazakhstan: '🇰🇿',
  korea: '🇰🇷',
  kor: '🇰🇷',
  kr: '🇰🇷',
  kyrgyzstan: '🇰🇬',
  latvia: '🇱🇻',
  lithuania: '🇱🇹',
  mexico: '🇲🇽',
  mex: '🇲🇽',
  md: '🇲🇩',
  mda: '🇲🇩',
  moldova: '🇲🇩',
  morocco: '🇲🇦',
  netherlands: '🇳🇱',
  ned: '🇳🇱',
  nl: '🇳🇱',
  nld: '🇳🇱',
  newzealand: '🇳🇿',
  nigeria: '🇳🇬',
  norway: '🇳🇴',
  pakistan: '🇵🇰',
  pe: '🇵🇪',
  per: '🇵🇪',
  peru: '🇵🇪',
  philippines: '🇵🇭',
  pl: '🇵🇱',
  pol: '🇵🇱',
  poland: '🇵🇱',
  polska: '🇵🇱',
  portugal: '🇵🇹',
  puertorico: '🇵🇷',
  qatar: '🇶🇦',
  romania: '🇷🇴',
  russia: '🇷🇺',
  rus: '🇷🇺',
  saudiarabia: '🇸🇦',
  scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  se: '🇸🇪',
  senegal: '🇸🇳',
  serbia: '🇷🇸',
  slovakia: '🇸🇰',
  southafrica: '🇿🇦',
  za: '🇿🇦',
  zaf: '🇿🇦',
  southkorea: '🇰🇷',
  spain: '🇪🇸',
  swe: '🇸🇪',
  sweden: '🇸🇪',
  switzerland: '🇨🇭',
  tajikistan: '🇹🇯',
  thailand: '🇹🇭',
  tunisia: '🇹🇳',
  turkey: '🇹🇷',
  ua: '🇺🇦',
  uae: '🇦🇪',
  uk: '🇬🇧',
  unitedarabemirates: '🇦🇪',
  unitedkingdom: '🇬🇧',
  unitedstates: '🇺🇸',
  unknown: '🏳️',
  us: '🇺🇸',
  usa: '🇺🇸',
  ukraine: '🇺🇦',
  ukr: '🇺🇦',
  unitedstatesofamerica: '🇺🇸',
  uzbekistan: '🇺🇿',
  uz: '🇺🇿',
  uzb: '🇺🇿',
  venezuela: '🇻🇪',
  wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  aus: '🇦🇺',
  dk: '🇩🇰',
  dnk: '🇩🇰',
}

/** Emoji drapeau pour un combattant (champ `country` du roster). */
export function getCountryFlagEmoji(country?: string | null): string {
  if (!country?.trim()) return '🏳️'
  const key = normalizeCountryKey(country)
  return COUNTRY_FLAGS[key] ?? '🏳️'
}

/** Libellé lisible du pays (conserve la casse d’origine si connue). */
export function formatCountryLabel(country?: string | null): string | null {
  if (!country?.trim() || normalizeCountryKey(country) === 'unknown') return null
  return country.trim()
}
